### ISSUE TITLE
Silence Argument for Bhsa

### ISSUE THREAD

**Issue by codykingham** [Dans-labs/text-fabric#28]
I would like a silence argument for `Bhsa` to keep things clean in my NB opening statements.

**Comment by dirkroorda** [comment]
I think there is a silent argument, but after my latest work on autodownloading, the silence argument is not honoured by all messages. Will have a look into it one of these days.

**Comment by dirkroorda** [comment]
I added an optional `silent=False` argument to `Bhsa()`, `Cunei()`, `Peshitta()` and `Syrnt()`. All non-error output will be suppressed. Also the lists of loaded features, links to API docs, etc.
