### ISSUE TITLE
TF is out of memory!

### ISSUE THREAD

**Issue by adamb924** [Dans-labs/text-fabric#29]
I'm getting an out-of-memory error message when I load the bhsa corpus. (I am able to load the srynt corpus.) I would think that my machine has enough memory. As shown in the screenshot below, I have 4.7 GB available when it failed to run. (The bump you see in the graph is where I tried to open the bhsa corpus.) I don't know if this is a text-fabric error, or if I truly don't have enough memory to display the corpus. If the latter is the case, it would be good if memory requirements were documented more specifically.

```
PS C:\Users\Adam\Desktop> text-fabric
This is Text-Fabric 6.3.1
specify data source [bhsa/peshitta/cunei/syrnt] > bhsa
Cleaning up remnant processes, if any ...
Loading data for bhsa. Please wait ...
Setting up TF kernel for bhsa
Using bhsa-c r1.4 in ~/text-fabric-data/etcbc/bhsa/tf/c
Using phono-c r1.1 in ~/text-fabric-data/etcbc/phono/tf/c
Using parallels-c r1.1 in ~/text-fabric-data/etcbc/parallels/tf/c
   |     1.02s T number               from C:\Users\Adam/text-fabric-data/etcbc/bhsa/tf/c
  4.68s Not all features could be loaded/computed
TF is out of memory!
If this happens and your computer has more than 3GB RAM on board:
Close all other programs and try again.
```

![untitled](https://user-images.githubusercontent.com/1312486/47583426-0bcc0880-d91d-11e8-8a9e-59ae0cdb42b9.png)

**Comment by dirkroorda** [comment]
I have done a series of tests, and I can load the bhsa on a windows VM with only 3 GB RAM. So I cannot quite understand what you encounter here.

**Comment by dirkroorda** [comment]
Do you run a 32-bit Python? In order to address more than 4GB of RAM, you need a 64 bit Python!

**Comment by adamb924** [comment]
Thank you; installing 64 bit Python solved the problem.
