### ISSUE TITLE
# search operator for features

### ISSUE THREAD

**Issue by camilstaps** [Dans-labs/text-fabric#3]
Is it possible to extend the search template language to allow `#` for features?

For example, I want to find sentences where אמר is followed by some ל+infinitive construct, but want to exclude the infinitive construct of אמר. I would then like to use the query below (or is there an easier way to do this with the current search template syntax?):

```
sentence
    clause
        word lex=>MR[
    < clause
        word lex=L
        <: word vt=infc lex#>MR[
```

**Comment by codykingham** [comment]
I second the need for a `!=` operator in TF search.

**Comment by dirkroorda** [comment]
There are now new possibilities:

* `nodetype feature` : feature is present and not None
* `nodetype feature!` : feature is not present or None
* `nodetype feature>val` : feature has value greater than val (numerical features only)
* `nodetype feature<val` : feature has value less than val (numerical features only)
* `nodetype feature~regexp` : feature matches regular expression (string features only)

So: `word vt=infc lex~(?!^>MR[)`

**Comment by dirkroorda** [comment]
Actually, this was an embarrasingly good suggestion. Regular expressions are nice, but clumsy when you just want to use them for the non-equality of values. So I have implemented the # after all. And saying `word vt#` means: feature vt has no value for word. 

It will be included in the next release.

**Comment by camilstaps** [comment]
Excellent, thanks!
