### ISSUE TITLE
Show Verse Labels in Condensed View

### ISSUE THREAD

**Issue by codykingham** [Dans-labs/text-fabric#31]
When using `B.show` with `condenseType=clause` the verse label no longer appears. This is undesirable since the reference is an important coordinate, regardless of whether the whole verse is displayed.

**Comment by dirkroorda** [comment]
Seems perfectly reasonable to me. I think I'll add an option (withPassage=True) to provide the passage of the first slot in the result tuple.

**Comment by dirkroorda** [comment]
The logic of providing a passage label to a plain / pretty display. There will be a new argument: `withPassage=True`

* if the node is a section node, it will have a passage label in its representation, `withPassage` has no effect
* all other nodes: the reference node is the first slot "under it". 
  `withPassage` is True: the passage label of the reference node will be produced.
* in plainTuple and prettyTuple: 
  * in uncondensed mode: 
    the reference node will be taken from the node that is "linked", if any, otherwise the first node
  * in condensed mode:
    the reference node will be taken from the container nodes

**Comment by dirkroorda** [comment]
Done
