### ISSUE TITLE
Add a A.showSetup

### ISSUE THREAD

**Issue by codykingham** [Dans-labs/text-fabric#32]
There is an `A.prettySetup`. I would like an `A.showSetup`. This is because I'm calling a lot of `A.show` in my NB, and constantly have to specify what I want condensed, that i want nodes, etc.

**Comment by dirkroorda** [comment]
Looks reasonable and doable. Will do it.

As an aside, prettySetup() in itself is problematic in some use cases, and the new showSetup() will be so too.

That is way I have also built a way to achieve the same effect without prettySetup: you pass the extra features to pretty() and friends.

The problem scenario occurs when you have one TF kernel that responds to multiple queries, possibly at the same time. When it is doing a prettySetup, the effects will be visible in to the pretty() executions of other processes. 

Anyway, in the single user case, prettySetup() and showSetup() are convenient ways to get your formatting options to all levels. So I continue to support that way.

**Comment by dirkroorda** [comment]
It is done: the functions are `displaySetup()` and `displayReset()`. With displaySetup you can override a bunch of defaults in displaying, selectively, such as the extra features to show, the features to suppress, the column that needs to be linked, the start and end position, the color map and highlights, and the condensing. 

All these params can also be passed directly to the functions. In that case they override the values given in displaySetup.

So it is three level, in order of priority:

* the values of the arguments explicitly passed to the function
* the values configured by the displaySetup
* the default (factory) values

Will be in the next release.
