### ISSUE TITLE
Better use of names

### ISSUE THREAD

**Issue by dirkroorda** [Dans-labs/text-fabric#6]
Direct use of names in atoms
===================== 

Take this example of a query with quantifiers

```
phrase
all:
  ^ w:word
have:
  ww:word pdp=verb
  w = ww
end:
```
This looks clumsy, and is causes by the fact that names (like `w`) cannot be used in places where an atom is expected. So I propose to lift that restriction, so that you can say

```
phrase
all:
  ^ w:word
have:
  w pdp=verb
end:
```

This should also work outside quantifiers.

I intend to implement this as mere syntactic sugar: during tokenization of the query the second form will be translated to the first form.

The parent node
============
Related to this: all quantifiers are relative to a parent atom. But there is no standard name
to refer to the parent atom. So if you want to say of a phrase
that if it contains a verb, its function should be Pred
you have to work like this:

```
p:phrase
all:
  ^ w:word pdp=verb
have:
  q:phrase function=Pred
  q = p
end:
```

but if `..` would be the name of the parent, you could say

```
phrase
all:
  ^ w:word pdp=verb
have:
  .. function=Pred
end:
```

This uses both proposed new devices: extended name usage, and `..` for the parent node of a quantifier.

**Comment by dirkroorda** [comment]
But as of now, I do not know what that means and how to implement it.
Let me try: if a quantifier may refer to names outside itself and its parent, then the quantifier does not only "quantify" its parent, but also the other thing, in your case, the c2 clause.

Example: find verses with at least two consecutive sentences.
The first of the sentences should have a clause c, and the second of the sentences
may not have a clause whose mother is c.

```
verse
  sentence
    c:clause
  :> sentence
  no:
    ^ clause
        -mother> c
    end:
```

Ok, this is understandable, but how to implement it?
When I compose auxiliary queries for quantifiers, I compose them from the atom and the templates inside the quantifier. 
But in this case, I need to use something bigger than the atom, I should go back right to the beginning. It becomes much harder to get the intended results from the auxiliary queries.

And if the template has an arbitrary number of quantifiers that reach out beyond their parents, I have not a clue which auxiliary templates I have to construct.

I think the step of no quantifiers to the present poor man's quantifiers is a smaller step than from the poor man's quantifiers to outward looking quantifiers!

**Comment by codykingham** [comment]
Yes I see the point. That introduces too many conflicts. It is better that the quantifier template only has access to its atom.

**Comment by dirkroorda** [comment]
Done (the parent node, the use of names in atoms).
