### ISSUE TITLE
Indentation Before the Quantifier

### ISSUE THREAD

**Issue by codykingham** [Dans-labs/text-fabric#7]
TFS currently relates quantifiers to the immediately preceding atom. This happens even when that atom is indented under another element:

```
clause
    phrase function=Pred
no:
    ^ word pdp=prep
end:
```

The quantifier here relates to the phrase and not the clause, despite the indentation being even with clause. 

Proposal: Use the indentation preceding the quantifier to make the link with the atom. The above query would then look like this:

```
clause
    phrase function=Pred
    no:
        ^ word pdp=prep
    end:
```

**Comment by codykingham** [comment]
This avoids awkward syntax like:
```
c1:clause
    phrase function=Pred
c2:clause
no:
    word pdp=prep
end:
c1=c2
```

**Comment by dirkroorda** [comment]
Yes. The rule I expressed in the docs is: quantifiers must follow their atom.
I intended also: with the same indentation. 
But clearly, I did not enforce that. Will be done.

**Comment by dirkroorda** [comment]
Done.
